export const COPY = {
  en: {
    addVideo: "Add video",
    addVideoLink: "Add video link",
    addVideosFromSettings: "Add videos from Parent settings.",
    approved: "Approved",
    approvedCount: (count: number) => `${count} approved videos`,
    approvedVideo: "Approved video",
    approvedVideos: "Approved videos",
    approveAll: "Approve all",
    approveAllConfirm: "Approve every video in the library?",
    approveAllVideos: "Approve all videos",
    back15: "Go back 15 seconds",
    cancel: "Cancel",
    checkingApprovedLibrary: "Checking the parent-approved library.",
    checkingVideoDetails: "Checking video details...",
    checkingPlaylist: "Checking playlist...",
    close: "Close",
    copyFailed: "Copy failed",
    copying: "Copying...",
    exportCopied: "Export copied",
    exportParentSettings: "Export parent settings",
    exitFullScreen: "Exit full screen",
    forward15: "Go forward 15 seconds",
    fullScreen: "Full screen",
    goHome: "Go home",
    hiddenVideos: "Hidden videos",
    hide: "Hide",
    hideAll: "Hide all",
    hideAllConfirm: "Hide every approved video from home?",
    hideAllVideos: "Hide all videos",
    home: "Home",
    importComplete: "Import complete.",
    importFailed: "Could not import this code.",
    importParentSettings: "Import parent settings",
    importSettings: "Import settings",
    importedVideoTitle: "Imported YouTube video",
    language: "Language",
    loadingVideo: "Loading video",
    nextVideo: "Next approved video",
    noApprovedVideos: "No approved videos yet",
    noVideosFound: (tab: "approved" | "hidden") => `No ${tab} videos found.`,
    mute: "Mute",
    openSettings: "Open settings",
    parentAdded: "Parent added",
    parentSettings: "Parent settings",
    pause: "Pause",
    pasteExportCode: "Paste KidTube export code",
    pasteImportCodeError: "Paste a valid KidTube export code.",
    pasteYoutubeLink: "Paste YouTube video or playlist link",
    pasteYoutubeLinkError: "Paste a valid YouTube video, playlist link, or video ID.",
    playlistAdded: (count: number) => `${count} playlist videos added.`,
    playlistNoVideos: "No videos found in this playlist.",
    playRecommendedVideo: "Play recommended video",
    playVideo: "Play video",
    previousVideo: "Previous approved video",
    readingImportCode: "Reading import code...",
    removeCompletely: "Remove completely",
    removeCompletelyLabel: (title: string) => `Remove ${title} completely`,
    resetAllVideos: "Reset all videos",
    resetAllVideosConfirm:
      "Reset to the default video list? Parent-added videos and hidden choices will be cleared.",
    repeatOneDisabled: "Repeat one disabled",
    repeatOneEnabled: "Repeat one enabled",
    search: "Search",
    searchApprovedVideos: "Search approved videos",
    searchPageTitle: (query: string) => `${query} - Search | KidTube`,
    searchVideos: "Search videos",
    show: "Show",
    showApprovedVideos: "Show approved videos",
    showHiddenVideos: "Show hidden videos",
    shuffleHome: "Shuffle home",
    switchLanguage: "Switch language",
    transferCodeShort: "Transfer code is too short.",
    transferInvalidVideo: "Transfer code contains an invalid video.",
    transferReadUnsupported: "This browser cannot read compressed transfer codes.",
    transferUnsupported: "Unsupported transfer code version.",
    unmute: "Unmute",
    useDarkMode: "Use dark mode",
    useLightMode: "Use light mode",
    videoControls: "Video controls",
    videoPlayerHelp:
      "Video player. Use left and right to seek, up and down for volume, and enter to play or pause.",
    videoSurface: (title: string) => `${title} video surface`,
    videoUnavailable: "Video unavailable",
    videoUnavailableMessage: "This video is hidden, removed, or not in this library.",
    volume: (value: number) => `Volume ${value}%`,
    volumeDown: "Volume down",
    volumeUp: "Volume up",
  },
  uz: {
    addVideo: "Qo'shish",
    addVideoLink: "Video havolasini qo'shish",
    addVideosFromSettings: "Ota-ona sozlamalari orqali video qo'shing.",
    approved: "Tanlangan",
    approvedCount: (count: number) => `${count} ta tanlangan video`,
    approvedVideo: "Tanlangan video",
    approvedVideos: "Tanlangan videolar",
    approveAll: "Barchasini tasdiqlash",
    approveAllConfirm: "Kutubxonadagi hamma videolar tasdiqlansinmi?",
    approveAllVideos: "Hamma videolarni tasdiqlash",
    back15: "15 soniya orqaga",
    cancel: "Bekor qilish",
    checkingApprovedLibrary: "Ota-ona tasdiqlagan kutubxona tekshirilmoqda.",
    checkingVideoDetails: "Video ma'lumotlari tekshirilmoqda...",
    checkingPlaylist: "Playlist tekshirilmoqda...",
    close: "Yopish",
    copyFailed: "Nusxalash amalga oshmadi",
    copying: "Nusxalanmoqda...",
    exportCopied: "Export nusxalandi",
    exportParentSettings: "Ota-ona sozlamalarini eksport qilish",
    exitFullScreen: "Full screendan chiqish",
    forward15: "15 soniya oldinga",
    fullScreen: "To'liq ekran",
    goHome: "Bosh sahifaga",
    hiddenVideos: "Yashirilgan videolar",
    hide: "Yashirish",
    hideAll: "Barchasini yashirish",
    hideAllConfirm: "Tanlangan hamma videolar bosh sahifadan yashirilsinmi?",
    hideAllVideos: "Hamma videolarni yashirish",
    home: "Bosh sahifa",
    importComplete: "Import tugadi.",
    importFailed: "Bu kodni import qilib bo'lmadi.",
    importParentSettings: "Ota-ona sozlamalarini import qilish",
    importSettings: "Sozlamalarni import qilish",
    importedVideoTitle: "Import qilingan YouTube videosi",
    language: "Til",
    loadingVideo: "Video yuklanmoqda",
    nextVideo: "Keyingi tanlangan video",
    noApprovedVideos: "Hali tanlangan video yo'q",
    noVideosFound: (tab: "approved" | "hidden") =>
      tab === "approved"
        ? "Tanlangan videolar topilmadi."
        : "Yashirilgan videolar topilmadi.",
    mute: "Ovozni o'chirish",
    openSettings: "Sozlamalarni ochish",
    parentAdded: "Ota-ona qo'shgan",
    parentSettings: "Ota-ona sozlamalari",
    pause: "Pauza",
    pasteExportCode: "KidTube export kodini kiriting",
    pasteImportCodeError: "To'g'ri KidTube export kodini kiriting.",
    pasteYoutubeLink: "YouTube video yoki playlist havolasini kiriting",
    pasteYoutubeLinkError: "To'g'ri YouTube video, playlist havolasi yoki video ID kiriting.",
    playlistAdded: (count: number) => `${count} ta playlist videosi qo'shildi.`,
    playlistNoVideos: "Bu playlistda video topilmadi.",
    playRecommendedVideo: "Tavsiya qilingan videoni ko'rish",
    playVideo: "Videoni ko'rish",
    previousVideo: "Oldingi tanlangan video",
    readingImportCode: "Import kodi o'qilmoqda...",
    removeCompletely: "Butunlay o'chirish",
    removeCompletelyLabel: (title: string) => `${title} butunlay o'chirilsin`,
    resetAllVideos: "Hamma videolarni reset qilish",
    resetAllVideosConfirm:
      "Default video ro'yxatiga qaytarilsinmi? Ota-ona qo'shgan videolar va yashirilgan tanlovlar tozalanadi.",
    repeatOneDisabled: "Bitta videoni takrorlash o'chirilgan",
    repeatOneEnabled: "Bitta videoni takrorlash yoqilgan",
    search: "Qidirish",
    searchApprovedVideos: "Tanlangan videolarni qidirish",
    searchPageTitle: (query: string) => `${query} - Qidiruv | KidTube`,
    searchVideos: "Videolarni qidirish",
    show: "Ko'rsatish",
    showApprovedVideos: "Tanlangan videolarni ko'rsatish",
    showHiddenVideos: "Yashirilgan videolarni ko'rsatish",
    shuffleHome: "Bosh sahifani aralashtirish",
    switchLanguage: "Tilni almashtirish",
    transferCodeShort: "Transfer kodi juda qisqa.",
    transferInvalidVideo: "Transfer kodida noto'g'ri video bor.",
    transferReadUnsupported: "Bu brauzer siqilgan transfer kodlarini o'qiy olmaydi.",
    transferUnsupported: "Transfer kodi versiyasi qo'llab-quvvatlanmaydi.",
    unmute: "Ovozni yoqish",
    useDarkMode: "Dark mode",
    useLightMode: "Light mode",
    videoControls: "Video boshqaruvlari",
    videoPlayerHelp:
      "Video player. Chap/o'ng bilan oldinga-orqaga, yuqori/past bilan ovoz, Enter bilan play/pause.",
    videoSurface: (title: string) => `${title} video oynasi`,
    videoUnavailable: "Video mavjud emas",
    videoUnavailableMessage: "Bu video yashirilgan, o'chirilgan yoki kutubxonada yo'q.",
    volume: (value: number) => `Ovoz ${value}%`,
    volumeDown: "Ovozni pasaytirish",
    volumeUp: "Ovozni ko'tarish",
  },
} as const;

export type CopyText = typeof COPY.en;
